[project]
name = "case-study-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chex>=0.1.91",
    "gradio>=6.4.0",
    "jax>=0.9.0",
    "transformers>=5.0.0",
]
