name: Lint Codebase

on:
  push:

  workflow_dispatch:


jobs:
  lint-codebase:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff-action@v3
        with:
          src: "../../"
      - run: ruff check --fix
      - run: ruff format

    
